In [2]:
import numpy as np

In [3]:
#Array Creation
a = np.arange(10,51,1)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [4]:
b = np.random.rand(3,3)
print(b)

[[0.43190834 0.81165886 0.94198595]
 [0.06225511 0.21655764 0.81336382]
 [0.52395236 0.46716594 0.94182002]]


In [5]:
#Array Attributes
#Shape of the array
b.shape

(3, 3)

In [6]:
#Size of the array
b.size

9

In [7]:
#Data Type of the array
b.dtype

dtype('float64')

In [10]:
#Basic Operations
#Adding 5 to every element of a 1D Array
c = np.arange(1,6,1)
d = c + 5
print(d)

[ 6  7  8  9 10]


In [11]:
#Multiplying 2 arrays element-wise
e = np.array([[1,2,3],[4,5,6]])
f = np.array([[7,8,9],[10,11,12]])
print(e * f)

[[ 7 16 27]
 [40 55 72]]


In [14]:
#Indexing and Slicing
g = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
g[:1,]

array([[1, 2, 3, 4, 5]])

In [19]:
g[:,4]

array([ 5, 10, 15, 20, 25])

In [22]:
#Printing subarray of first 3 rows and first 2 columns
g[0:3,0:2]

array([[ 1,  2],
       [ 6,  7],
       [11, 12]])

In [38]:
#Aggregation
#Creating a 10-Element Array of random integers between 1 and 100
x = np.floor(np.random.rand(10) * 99) + 1
print(x.astype(int))

[36 11 39 40 12 66 96 44 36 45]


In [40]:
#Finding the maximum value
print(x.max())

96.0


In [41]:
#Finding the minimum value
print(x.min())

11.0


In [42]:
#Finding the mean
print(x.mean())

42.5


In [43]:
#Finding the standard deviation
print(x.std())

23.3420221917468


In [45]:
#Converting a 1D array of numbers from 1 to 12 into a 3 * 4 matrix
s = np.arange(1,13,1)
s.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [50]:
#Broadcasting
#Create a 3 * 3 matrix of ones. Add a 1D Array [1,2,3] to each row
one_matrix = np.ones((3,3))
add_matrix = np.array([1,2,3])
result = one_matrix + add_matrix
print(result)

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [55]:
#Creating a 1D array of random integers between 1 and 50
matrix = np.floor(np.random.rand(10)*50) + 1
print(matrix.astype(int))

[23 12  6 35 17  1  2 18  4 16]


In [57]:
#Extract all elements that are divisible by 5
extracted_elements = matrix[matrix % 5 == 0]
print(extracted_elements.astype(int))

[35]


In [60]:
#Matrix Multiplication (or) Dot Product
matrix1 = np.arange(1,7,1).reshape(2,3)
matrix2 = np.arange(7,13,1).reshape(3,2)
print(matrix1.dot(matrix2))

[[ 58  64]
 [139 154]]


In [67]:
#Advanced Indexing
#Given an 4 * 4 array, use fancy indexing to extract the diagonal elements
special_matrix = np.floor(np.random.rand(16) * 10) + 1
updated_matrix = special_matrix.reshape((4,4))
print(updated_matrix.astype(int))

[[ 6  5  5 10]
 [ 4  9  2  6]
 [ 7  8  8  3]
 [10  3  1  9]]


In [68]:
diagonal_elements = updated_matrix[[0,1,2,3],[0,1,2,3]]
print(diagonal_elements)

[6. 9. 8. 9.]
